query GetProjects {
  getProjects {
    id
    name
    description
  }
}
query GetProjectById($getProjectByIdId: String!) {
  getProjectById(id: $getProjectByIdId) {
    id
    name
    description
  }
}
mutation CreateProject($project: CreateProjectDto!) {
  createProject(project: $project) {
    id
    name
  }
}
mutation UpdateProject($project: UpdateProjectDto!) {
  updateProject(project: $project) {
    id
    name
  }
}
mutation DeleteProject($deleteProjectId: String!) {
  deleteProject(id: $deleteProjectId) {
    success
    message
  }
}
